#!/bin/bash
# .archy/archy-runner.sh
# Generated by Archy Bootstrap — the outer autopilot loop
#
# Usage:
#   ./archy-runner.sh              # Normal autopilot
#   ./archy-runner.sh --dry-run    # Preview mode (no execution)
#   ./archy-runner.sh --max 10     # Limit to 10 tasks
#
# This script runs one AI session per task in a fresh context.
# The AI handles ONE spec, outputs a Session Summary, and exits.
# This script manages the loop, logging, and failure handling.

set -euo pipefail

# ─── Load Configuration ──────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/runner-config.sh"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Config not found: $CONFIG_FILE"
    echo "   Run Archy Bootstrap first, or create runner-config.sh manually."
    exit 1
fi

source "$CONFIG_FILE"

DRY_RUN=${DRY_RUN:-false}
MAX_TASKS=${MAX_TASKS:-50}
PAUSE_BETWEEN=${PAUSE_BETWEEN:-2}
PROJECT_NAME=${PROJECT_NAME:-$(basename "$(pwd)")}
SESSION_LOG=${SESSION_LOG:-"$SCRIPT_DIR/sessions.log"}
AUTO_GIT=${AUTO_GIT:-true}
AUTO_CREATE_BRANCH=${AUTO_CREATE_BRANCH:-true}
AUTO_COMMIT=${AUTO_COMMIT:-true}
AUTO_MERGE=${AUTO_MERGE:-true}
AUTO_DELETE_BRANCH=${AUTO_DELETE_BRANCH:-false}
GIT_BASE_BRANCH=${GIT_BASE_BRANCH:-dev}
GIT_FEATURE_PREFIX=${GIT_FEATURE_PREFIX:-feature}
GIT_COMMIT_PREFIX=${GIT_COMMIT_PREFIX:-feat}

# ─── Parse CLI Arguments ─────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --max)
            MAX_TASKS="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: archy-runner.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --dry-run    Preview mode — show what would run without executing"
            echo "  --max N      Maximum number of tasks to execute (default: $MAX_TASKS)"
            echo "  --help       Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Run with --help for usage."
            exit 1
            ;;
    esac
done

# ─── Validate Environment ────────────────────────────────────────────
if [ -z "${BASE_PROMPT:-}" ] || [ ! -f "$BASE_PROMPT" ]; then
    echo "❌ Base prompt not found or unset: ${BASE_PROMPT:-<unset>}"
    echo "   Run Archy Bootstrap first."
    exit 1
fi

if [ -z "${MISSION_CONTROL:-}" ] || [ ! -f "$MISSION_CONTROL" ]; then
    echo "❌ Mission control not found or unset: ${MISSION_CONTROL:-<unset>}"
    echo "   Run Archy Bootstrap first."
    exit 1
fi

if [ -z "${AI_CMD:-}" ] || ! command -v "$AI_CMD" &> /dev/null; then
    echo "❌ AI CLI tool not found or unset: ${AI_CMD:-<unset>}"
    echo "   Install it or update runner-config.sh with the correct command."
    exit 1
fi

# ─── Initialize ──────────────────────────────────────────────────────
COMPLETED=0
FAILED=0
SESSION_NUM=0
START_TIME=$(date +%s)

# Create session log if it doesn't exist
touch "$SESSION_LOG"

# ─── Header ──────────────────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════╗"
echo "║  🚀 Archy Runner — Autopilot Mode               ║"
echo "║  Project: $PROJECT_NAME"
echo "║  Max Tasks: $MAX_TASKS"
if [ "${DRY_RUN:-false}" = true ]; then
echo "║  ⚠️  DRY RUN — No sessions will be executed      ║"
fi
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ─── Log Helper ──────────────────────────────────────────────────────
log_session() {
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "" >> "$SESSION_LOG"
    echo "=== Session $SESSION_NUM | $timestamp ===" >> "$SESSION_LOG"
    echo "$1" >> "$SESSION_LOG"
}

get_next_spec() {
    local line
    line=$(grep -m 1 '^\- \[ \]' "$MISSION_CONTROL" || true)
    echo "$line" | sed -n 's/.*\([A-Za-z0-9._-]\+\.md\).*/\1/p'
}

git_is_ready() {
    [ "${AUTO_GIT:-false}" = true ] && command -v git &> /dev/null && [ -d ".git" ]
}

# ─── Main Loop ───────────────────────────────────────────────────────
while [ $COMPLETED -lt $MAX_TASKS ]; do
    SESSION_NUM=$((SESSION_NUM + 1))

    # Count pending tasks
    PENDING=$(grep -c '^\- \[ \]' "$MISSION_CONTROL" 2>/dev/null || echo 0)
    BLOCKED=$(grep -c '^\- \[!\]' "$MISSION_CONTROL" 2>/dev/null || echo 0)
    DONE=$(grep -c '^\- \[x\]' "$MISSION_CONTROL" 2>/dev/null || echo 0)

    # Check if queue is empty
    if [ "$PENDING" -eq 0 ]; then
        echo "✅ All tasks completed or queue empty."
        echo ""
        echo "📊 Final Stats:"
        echo "   Completed this run: $COMPLETED"
        echo "   Failed: $FAILED"
        echo "   Already done: $DONE"
        echo "   Blocked: $BLOCKED"
        log_session "QUEUE EMPTY — Run complete. Completed: $COMPLETED, Failed: $FAILED"
        break
    fi

    # Display status
    echo "┌──────────────────────────────────────────"
    echo "│ 📋 Session $SESSION_NUM"
    echo "│ Pending: $PENDING | Done: $DONE | Blocked: $BLOCKED"
    echo "└──────────────────────────────────────────"

    SPEC_FILE=$(get_next_spec)
    SPEC_ID="${SPEC_FILE%.md}"
    FEATURE_BRANCH=""
    ACTIVE_BRANCH=""

    if git_is_ready; then
        if [ -n "$SPEC_ID" ] && [ "${AUTO_CREATE_BRANCH:-false}" = true ]; then
            ACTIVE_BRANCH="$GIT_BASE_BRANCH"
            git checkout "$ACTIVE_BRANCH" >/dev/null 2>&1 || true
            git pull --ff-only origin "$ACTIVE_BRANCH" >/dev/null 2>&1 || true
            FEATURE_BRANCH="$GIT_FEATURE_PREFIX/$SPEC_ID"
            if git show-ref --verify --quiet "refs/heads/$FEATURE_BRANCH"; then
                git checkout "$FEATURE_BRANCH" >/dev/null 2>&1 || true
            else
                git checkout -b "$FEATURE_BRANCH" >/dev/null 2>&1 || true
            fi
        fi
    fi

    # Dry run mode
    if [ "${DRY_RUN:-false}" = true ]; then
        echo "   🔍 [DRY RUN] Would execute: $AI_CMD $AI_PROMPT_FLAG \"execute @$BASE_PROMPT\""
        echo "   🔍 [DRY RUN] Pending tasks:"
        grep '^\- \[ \]' "$MISSION_CONTROL" | head -5 | while read -r line; do
            echo "      $line"
        done
        echo ""
        log_session "[DRY RUN] Would execute session. Pending: $PENDING"
        COMPLETED=$((COMPLETED + 1))
        continue
    fi

    # Execute one task in a fresh AI session
    echo "   🔨 Launching AI session..."
    echo ""

    # Create a temporary file to capture output while streaming to stdout
    SESSION_TMP=$(mktemp)
    if command -v script &> /dev/null; then
        script -q -e -c "$AI_CMD $AI_PROMPT_FLAG \"execute @$BASE_PROMPT\"" "$SESSION_TMP"
        EXIT_CODE=$?
        SESSION_OUTPUT=$(sed '/^Script (started|done) on/d' "$SESSION_TMP")
    else
        $AI_CMD $AI_PROMPT_FLAG "execute @$BASE_PROMPT" 2>&1 | tee "$SESSION_TMP"
        EXIT_CODE=${PIPESTATUS[0]}
        SESSION_OUTPUT=$(cat "$SESSION_TMP")
    fi
    rm "$SESSION_TMP"

    if [ $EXIT_CODE -ne 0 ]; then
        echo "   ⚠️  Session exited with error (code $EXIT_CODE)"
        FAILED=$((FAILED + 1))
        log_session "FAILED (exit code $EXIT_CODE)
$SESSION_OUTPUT"

        # Check for consecutive failures
        if [ $FAILED -ge 3 ]; then
            echo ""
            echo "🛑 3 consecutive failures. Halting autopilot."
            echo "   Check .archy/sessions.log for details."
            log_session "HALTED — 3 consecutive failures"
            exit 1
        fi

        echo "   Continuing to next task..."
        sleep "$PAUSE_BETWEEN"
        continue
    fi

    # Log the session output
    log_session "$SESSION_OUTPUT"

    # Check if session summary indicates failure
    if echo "$SESSION_OUTPUT" | grep -q "Status: FAILED\|Status: ESCALATED"; then
        echo "   ⚠️  Task reported FAILED or ESCALATED"
        FAILED=$((FAILED + 1))

        if [ $FAILED -ge 3 ]; then
            echo ""
            echo "🛑 3 failures reached. Halting autopilot."
            echo "   Check .archy/sessions.log for details."
            log_session "HALTED — 3 failures reached"
            exit 1
        fi
    else
        COMPLETED=$((COMPLETED + 1))
        FAILED=0  # Reset consecutive failure counter on success
        echo "   ✅ Task completed successfully"
        if git_is_ready; then
            if [ "${AUTO_COMMIT:-false}" = true ] && [ -n "$SPEC_ID" ]; then
                if ! git diff --quiet || ! git diff --cached --quiet; then
                    git add -A
                    git commit -m "$GIT_COMMIT_PREFIX: $SPEC_ID" >/dev/null 2>&1 || true
                fi
            fi
            if [ "${AUTO_MERGE:-false}" = true ] && [ -n "$FEATURE_BRANCH" ]; then
                git checkout "$GIT_BASE_BRANCH" >/dev/null 2>&1 || true
                git pull --ff-only origin "$GIT_BASE_BRANCH" >/dev/null 2>&1 || true
                if git merge --no-ff "$FEATURE_BRANCH" -m "merge: $SPEC_ID" >/dev/null 2>&1; then
                    if [ "${AUTO_DELETE_BRANCH:-false}" = true ]; then
                        git branch -d "$FEATURE_BRANCH" >/dev/null 2>&1 || true
                    fi
                else
                    echo "   ⚠️  Merge failed for $FEATURE_BRANCH into $GIT_BASE_BRANCH"
                fi
            fi
        fi
    fi

    echo ""

    # Pause between sessions
    sleep "$PAUSE_BETWEEN"
done

# ─── Summary ─────────────────────────────────────────────────────────
END_TIME=$(date +%s)
ELAPSED=$(( END_TIME - START_TIME ))
MINUTES=$(( ELAPSED / 60 ))
SECONDS=$(( ELAPSED % 60 ))

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  🏁 Autopilot Run Complete                       ║"
echo "║  Tasks Completed: $COMPLETED"
echo "║  Tasks Failed: $FAILED"
echo "║  Time Elapsed: ${MINUTES}m ${SECONDS}s"
echo "║  Session Log: $SESSION_LOG"
echo "╚══════════════════════════════════════════════════╝"

log_session "RUN COMPLETE — Completed: $COMPLETED, Failed: $FAILED, Time: ${MINUTES}m ${SECONDS}s"
